# Generated by Django 5.0.6 on 2024-06-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_cost_vehicle_distance_vehicle_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField()),
                ('cost_of_purchase', models.FloatField()),
                ('count', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='vehicles.organization')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_inventory', to='vehicles.vehicle')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inventory', to='vehicles.parkinglot')),
            ],
        ),
    ]
