# Generated by Django 5.0.6 on 2024-06-28 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_warehouseinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('details', models.TextField()),
                ('expense', models.FloatField()),
                ('income', models.FloatField(default=0.0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.organization')),
                ('reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.warehouseinventory')),
            ],
        ),
    ]
