# Generated by Django 5.0.6 on 2024-06-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_alter_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('emissions_per_unit_fuel', models.FloatField()),
                ('cost_per_unit_fuel', models.FloatField()),
                ('cost_uncertainty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_per_km', models.FloatField()),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.fuel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='vehicles.vehicle')),
            ],
        ),
    ]
