# Generated by Django 5.0.6 on 2024-07-01 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_vehiclefuel_vehicle_vehiclefuel_vehicle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('carbon_emission', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.organization')),
            ],
        ),
    ]
