# Generated by Django 5.0.6 on 2024-07-01 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_emissiontarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('size', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=255)),
                ('demand', models.IntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.organization')),
            ],
        ),
    ]
