# Generated by Django 5.0.6 on 2024-07-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_distancetravelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancetravelled',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.warehouseinventory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.warehouseinventory'),
        ),
    ]
