# Generated by Django 5.0.6 on 2024-07-04 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_distancetravelled_vehicle_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_year', models.IntegerField()),
                ('resale_value_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('insurance_cost_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maintenance_cost_percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.organization')),
            ],
        ),
    ]
