from django.urls import path
from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('vehicles', views.vehicles, name='vehicles'),
    path('details/<int:id>', views.details, name='details'),
    path('update/<int:id>', views.update, name='update'),    
    path('updatesub/<int:id>', views.updatesub, name='updatesub'),      
    path('deletesub/<int:id>', views.deletesub, name='deletesub'),          
    path('create', views.create, name='create'),    
    path('createsub',views.createsub, name='createsub'),      
    path('api/', views.vehicleView.as_view()),
    path('organization', views.organization, name='organization'),
    path('org_details/<int:id>', views.org_details, name='org_details'),
    path('org_create', views.org_create, name='org_create'),
    path('org_createsub', views.org_createsub, name='org_createsub'),
    path('org_update/<int:id>', views.org_update, name='org_update'),
    path('org_updatesub/<int:id>', views.org_updatesub, name='org_updatesub'),
    path('org_deletesub/<int:id>', views.org_deletesub, name='org_deletesub'),
    path('api/organization/', views.OrganizationView.as_view()),
    path('organization/<int:org_id>/parkinglots', views.parkinglots, name='parkinglots'),
    path('organization/<int:org_id>/parkinglot_create', views.parkinglot_create, name='parkinglot_create'),
    path('organization/<int:org_id>/parkinglot_createsub', views.parkinglot_createsub, name='parkinglot_createsub'),
    path('organization/<int:org_id>/parkinglot_update/<int:pl_id>', views.parkinglot_update, name='parkinglot_update'),
    path('organization/<int:org_id>/parkinglot_updatesub/<int:pl_id>', views.parkinglot_updatesub, name='parkinglot_updatesub'),
    path('organization/<int:org_id>/parkinglot_deletesub/<int:pl_id>', views.parkinglot_deletesub, name='parkinglot_deletesub'),
    path('api/parkinglots/', views.ParkingLotView.as_view()),
    path('organization/<int:org_id>/warehouseinventory/', views.warehouseinventory_list, name='warehouseinventory_list'),
    path('organization/<int:org_id>/warehouseinventory_create/', views.warehouseinventory_create, name='warehouseinventory_create'),
    path('organization/<int:org_id>/warehouseinventory_createsub/', views.warehouseinventory_createsub, name='warehouseinventory_createsub'),
    path('organization/<int:org_id>/warehouseinventory_update/<int:inventory_id>/', views.warehouseinventory_update, name='warehouseinventory_update'),
    path('organization/<int:org_id>/warehouseinventory_updatesub/<int:inventory_id>/', views.warehouseinventory_updatesub, name='warehouseinventory_updatesub'),
    path('organization/<int:org_id>/warehouseinventory_deletesub/<int:inventory_id>/', views.warehouseinventory_deletesub, name='warehouseinventory_deletesub'),
    path('api/warehouseinventory/', views.WarehouseInventoryView.as_view()),
    path('organization/<int:org_id>/warehouseinventory/additionalreport', views.additionalreport, name='additionalreport'),
    path('transactions/<int:organization_id>/', views.transaction_report, name='transaction_report'),
    path('fuels/', views.fuels, name='fuels'),
    path('fuel_update/<int:id>/', views.fuel_update, name='fuel_update'),
    path('fuel_updatesub/<int:id>/', views.fuel_updatesub, name='fuel_updatesub'),
    path('fuel_deletesub/<int:id>/', views.fuel_deletesub, name='fuel_deletesub'),
    path('fuel_create/', views.fuel_create, name='fuel_create'),
    path('fuel_createsub/', views.fuel_createsub, name='fuel_createsub'),
    path('api/fuels/', views.FuelView.as_view()),
    path('vehicle_fuels/', views.vehicle_fuels, name='vehicle_fuels'),
    path('vehicle_fuel_update/<int:id>/', views.vehicle_fuel_update, name='vehicle_fuel_update'),
    path('vehicle_fuel_updatesub/<int:id>/', views.vehicle_fuel_updatesub, name='vehicle_fuel_updatesub'),
    path('vehicle_fuel_deletesub/<int:id>/', views.vehicle_fuel_deletesub, name='vehicle_fuel_deletesub'),
    path('vehicle_fuel_create/', views.vehicle_fuel_create, name='vehicle_fuel_create'),
    path('vehicle_fuel_createsub/', views.vehicle_fuel_createsub, name='vehicle_fuel_createsub'),
    path('api/vehicle_fuels/', views.VehicleFuelView.as_view()),
    path('emissiontargetlist/<int:org_id>', views.emission_target_list, name='emission_target_list'),
    path('emissiontarget_create/<int:org_id>', views.emission_target_create, name='emission_target_create'),
    path('emissiontarget_createsub/<int:org_id>', views.emission_target_createsub, name='emission_target_createsub'),
    path('emissiontarget_update/<int:id>', views.emission_target_update, name='emission_target_update'),
    path('emissiontarget_updatesub/<int:id>', views.emission_target_updatesub, name='emission_target_updatesub'),
    path('emissiontarget_deletesub/<int:id>', views.emission_target_deletesub, name='emission_target_deletesub'),
    path('api/emissiontarget/', views.EmissionTargetView.as_view()),
    path('fleetdemandlist/<int:org_id>', views.fleet_demand_list, name='fleet_demand_list'),
    path('fleetdemand_create/<int:org_id>', views.fleet_demand_create, name='fleet_demand_create'),
    path('fleetdemand_createsub/<int:org_id>', views.fleet_demand_createsub, name='fleet_demand_createsub'),
    path('fleetdemand_update/<int:id>', views.fleet_demand_update, name='fleet_demand_update'),
    path('fleetdemand_updatesub/<int:id>', views.fleet_demand_updatesub, name='fleet_demand_updatesub'),
    path('fleetdemand_deletesub/<int:id>', views.fleet_demand_deletesub, name='fleet_demand_deletesub'),
    path('api/fleetdemand/', views.FleetDemandView.as_view()),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distancetravelledlist/', views.distancetravelledlist, name='distancetravelledlist'),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distance_travelled_details/<int:distance_id>/', views.distance_travelled_details, name='distance_travelled_details'),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distance_travelled_create/', views.distance_travelled_create, name='distance_travelled_create'),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distance_travelled_createsub/', views.distance_travelled_createsub, name='distance_travelled_createsub'),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distance_travelled_update/<int:distance_id>/', views.distance_travelled_update, name='distance_travelled_update'),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distance_travelled_updatesub/<int:distance_id>/', views.distance_travelled_updatesub, name='distance_travelled_updatesub'),
    path('organization/<int:org_id>/warehouseinventory/<int:inventory_id>/distance_travelled_deletesub/<int:distance_id>/', views.distance_travelled_deletesub, name='distance_travelled_deletesub'),
    path('api/distance_travelled/', views.DistanceTravelledView.as_view()),
]
